implemented better practices

diff --git a/handbrake-converter b/handbrake-converter
--- a/handbrake-converter
+++ b/handbrake-converter
@@ -1,27 +1,27 @@
 #!/bin/bash
-#VERSION=1.9####################################################################
+################################################################################
 # Revision Log
-# VERSION=0.0 - Conversion works
+# VERSION=0.0 - Initial commit, Conversion works
 # VERSION=0.1 - Rename Function added
 # VERSION=0.2 - HandBrakeCLI installed check
 # VERSION=0.3 - ReFormatted Code into functions
 # VERSION=0.4 - Added download link to Install Check
-# VERSION=0.5 - Corrected Rename function
-# VERSION=0.6 - Adding more video formats to rename function
-# VERSION=0.7 - Added OS Check to work with both LINUX and MAC OSX
-# VERSION=0.8 - Added a check before renames to verify file type existance
-# VERSION=0.9 - Added color to the COMPLETE statement
-# VERSION=1.0 - Added mpeg format to rename function
-# VERSION=1.1 - Remove source files, via confirmation
-# VERSION=1.2 - Remove source files, without individual file confirmation
-# VERSION=1.3 - Removed Comments
-# VERSION=1.4 - Adding extra checking to remove_src function
-# VERSION=1.5 - Working on self updating
-# VERSION=1.6 - Removed rename function, was able to do rename within convert function
-# VERSION=1.7 - Added Logic to check the ToBeConverted directory before starting Conversion
-# VERSION=1.8 - If the machine is OSX, when the script ends you get a pop up window
-# VERSION=1.9 - Changing pidfile location
-# VERSION=1.9.1 - Cleanup on the abort section
+# VERSION=0.4.1 - Corrected Rename function
+# VERSION=0.4.2 - Adding more video formats to rename function
+# VERSION=0.5 - Added OS Check to work with both LINUX and MAC OSX
+# VERSION=0.5.1 - Added a check before renames to verify file type existance
+# VERSION=0.5.2 - Added color to the COMPLETE statement
+# VERSION=0.5.3 - Added mpeg format to rename function
+# VERSION=0.6 - Remove source files, via confirmation
+# VERSION=0.7 - Remove source files, without individual file confirmation
+# VERSION=0.7.1 - Removed Comments
+# VERSION=0.7.2 - Adding extra checking to remove_src function
+# VERSION=0.8 - Removed rename function, was able to do rename within convert function
+# VERSION=0.9 - Added Logic to check the ToBeConverted directory before starting Conversion
+# VERSION=1.0 - If the machine is OSX, when the script ends you get a pop up window
+# VERSION=1.0.1 - Changing pidfile location
+# VERSION=1.0.2 - Cleanup on the abort section
+# VERSION=1.0.3 - Wrapped code into functions, updated function naming conventions, added more comments
 ################################################################################
 # This script converts any kind of video the HandBrake CLI can handle
 # into a 1000 kbit MPEG4 video and shrinks it down to a max width of 640 px.
@@ -32,6 +32,7 @@
 # files in that directory.
 #
 ################################################################################
+script_version="1.0.3"
 ################################
 ####### Color Variables ########
 ################################
@@ -42,22 +43,30 @@ reset=`tput sgr0`
 ################################
 ######## Process Check ########
 ################################
-
+function f_process_check {
 workingdir=`pwd`
 pidfile=${workingdir}/handbrake-converter.pid
 checkprocess=`ps -ef | grep handbrake-convert | grep -v grep | awk {' print $2 '}`
 
 if [[ -f $pidfile ]]; then
   echo "Script already running, Aborting!"
-  exit 0
+  exit 1
 fi
 
 touch $pidfile
 echo $checkprocess > $pidfile
+}
+################################
+###### PID file Cleanup ########
+################################
+function f_pid_cleanup {
+  rm -f $pidfile
+}
 
 ################################
 ########## OS Check ############
 ################################
+function f_os_check {
 platform='unknown'
 unamestr=`uname`
 if [[ "$unamestr" == 'Darwin' ]]; then
@@ -86,10 +95,11 @@ elif [[ "$unamestr" == 'Linux' ]]; then
      echo "Creating $OUT"
    fi
 fi
-
+}
 ################################
 ## HandBrakeCLI Install Check ##
 ################################
+function f_handbrakecli_installed_check {
 if [[ "$platform" == 'Darwin' ]]; then
   if [ ! -f /usr/local/bin/HandBrakeCLI ]; then
     echo "HandBrakeCLI IS NOT INSTALLED!"
@@ -106,19 +116,25 @@ if [[ "$platform" == 'Linux' ]]; then
     exit 1
   fi
 fi
-
+}
 ################################
 #### Check Converted Folder ####
 ################################
-function pre_convert {
+function f_pre_convert_checks {
   if [[ -z `ls $IN` ]]; then
     echo "No files to convert, Aborting!"
-    rm -f $pidfile
+    if [[ "platform" == 'Darwin' ]]; then
+      osascript -e 'display alert "No files to convert" message "No files to convert, Aborting!"'
+    fi
+    f_pid_cleanup
     exit 0
   fi
   if [[ ! -z `ls $OUT` ]]; then
     echo "Cleanup Converted Directory! Aborting!"
-    rm -f $pidfile
+    if [[ "platform" == 'Darwin' ]]; then
+      osascript -e 'display alert "Files still remain in Converted directory" message "Please move files to another location, Aborting!"'
+    fi
+    f_pid_cleanup
     exit 0
   fi
 }
@@ -126,7 +142,7 @@ function pre_convert {
 ################################
 ##### Conversion Function ######
 ################################
-function convert {
+function f_convert {
     #Use global Variables for INPUT and OUTPUT
     cd "$IN"
     for InputItem in *;do
@@ -137,7 +153,7 @@ function convert {
 ################################
 ##### Remove Source Files ######
 ################################
-function remove_src {
+function f_remove_src {
   ToBeCount=`ls -l $IN 2>/dev/null | wc -l`
   ConvertCount=`ls -l $OUT 2>/dev/null | wc -l`
   if [ $ToBeCount == $ConvertCount ]; then
@@ -157,9 +173,14 @@ function remove_src {
   fi
 }
 
-#Main
-pre_convert
-convert
-remove_src
-rm -f $pidfile
+#Main Script
+f_process_check
+f_os_check
+f_handbrakecli_installed_check
+f_pre_convert_checks
+f_convert
+f_remove_src
+f_pid_cleanup
+
+## Exit Script ##
 exit 0
